FROM node:16.18.0
# create & set working directory
RUN mkdir -p /src
WORKDIR /src
# copy source files
COPY . /src
# install dependencies
RUN npm install
# start app
RUN npm run build
EXPOSE 3000
# start app
CMD ["npm", "start"]


### CREAR LA IMAGEN LOCALMENTE
### docker build --tag melanialejandralopez/frontend-proyecto .

### CORRER LA IMAGEN
### docker run -p 3000:3000 melanialejandralopez/frontend-proyecto

### SUBIR LA IMAGEN
### docker push melanialejandralopez/frontend-proyecto