#Inicio docker-compose
version: "3" # Se indica el numero de version
# usar una network interna para prueba
networks:
  my-network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
services:
  mysql_db:
    container_name: mysql_db
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: mysql1234
    ports:
      - '3306:3306'
    volumes:
      - './data-mysql/:/var/lib/mysql'
    networks:
      my-network:
        ipv4_address: 172.18.0.6
  redis:
    container_name: redisv
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - './data-redis/:/data'
    networks:
      my-network:
        ipv4_address: 172.18.0.7
  grpc_server:
    container_name: grpc_server
    image: 'melanialejandralopez/so1_proyecto_grpc_server'
    build: ./gRPC-Server
    ports:
      - '50051:50051'
    depends_on:
      - mysql_db
    networks:
      my-network:
        ipv4_address: 172.18.0.2
  grpc_client:
    container_name: grpc_client
    image: 'melanialejandralopez/so1_proyecto_grpc_lient'
    build: ./gRPC-Client-api
    ports:
      - '3300:3300'
    depends_on:
      - grpc_server
    networks:
      my-network:
        ipv4_address: 172.18.0.3
  redissub:
    image: 'melanialejandralopez/so1_proyecto_redissub'
    build: ./redisSub
    container_name: redissub
    depends_on:
      - mysql_db
      - redis
    networks:
      my-network:
        ipv4_address: 172.18.0.5
  redispub:
    image: 'melanialejandralopez/so1_proyecto_redispub'
    build: ./redispub
    ports:
      - '3400:3400' # arreglar puertos 
    container_name: redispub
    depends_on:
      - mysql_db
      - redis
    networks:
      my-network:
        ipv4_address: 172.18.0.4
  
  api_server:
    container_name: api_server
    image: 'melanialejandralopez/so1_proyecto_api_server'
    build: ./api
    ports:
      - '4200:4200' 
    depends_on:
      - mysql_db
      - grpc_server
    networks:
      my-network:
        ipv4_address: 172.18.0.8
