apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/websocket-service: "service-server"
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST
spec:
  rules:
  - host: api.34.31.111.69.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-api
            port:
              number: 4200
  - host: 34.31.111.69.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: error-injector
            port:
              number: 3300

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: error-injector
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 4200;
            location / {
                return 500;
            }
        }
        server {
          listen 3300;
            location / {
                return 500;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-injector
  labels:
    app: error-injector
spec:
  selector:
    matchLabels:
      app: error-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: error-injector
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: error-injector
---
apiVersion: v1
kind: Service
metadata:
  name: error-injector
spec:
  ports:
  - name: service
    port: 3300
  selector:
    app: error-injector
---
apiVersion: split.smi-spec.io/v1alpha3
kind: TrafficSplit
metadata:
  name: error-split
spec:
  service: error-injector
  backends:
  - service: service-grpc
    weight: 50m
  - service: service-pub-sub
    weight: 50m
  - service: error-injector
    weight: 0m

